name: CI - Build & Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: |
          npm ci

      - name: Build React App from Client Directory
        run: |
          echo "=== Building React App ==="
          echo "Current directory: $(pwd)"
          echo "Vite config location:"
          ls -la vite.config.ts
          echo "Client directory:"
          ls -la client/

          # Try building with explicit memory settings
          export NODE_OPTIONS="--max-old-space-size=2048"
          npm run build:client
          echo "Build completed with exit code: $?"

      - name: Debug build output
        run: |
          echo "=== Checking build output ==="
          ls -la dist/
          echo "=== Checking dist/public ==="
          ls -la dist/public/ || echo "dist/public directory not found"
          echo "=== Looking for index.html ==="
          find . -name "index.html" -type f
          echo "=== All files in dist ==="
          find dist/ -type f | head -20

      - name: Create frontend archive
        run: |
          # Check multiple possible build output locations
          if [ -d "dist/public" ] && [ "$(ls -A dist/public)" ]; then
            echo "✅ Found build output in dist/public"
            BUILD_DIR="dist/public"
          elif [ -d "client/dist" ] && [ "$(ls -A client/dist)" ]; then
            echo "✅ Found build output in client/dist"
            BUILD_DIR="client/dist"
          elif [ -d "dist" ] && [ "$(ls -A dist)" ] && [ -f "dist/index.html" ]; then
            echo "✅ Found build output in dist"
            BUILD_DIR="dist"
          else
            echo "❌ No build output found in expected locations"
            echo "Searching for index.html files:"
            find . -name "index.html" -type f
            echo "Available directories:"
            find . -type d -name "*dist*" -o -name "*build*" -o -name "*public*"
            exit 1
          fi

          echo "Creating archive from $BUILD_DIR"
          cd "$BUILD_DIR"
          tar -czf ../../frontend-build.tar.gz .
          cd ../..
          ls -la frontend-build.tar.gz
          echo "Archive contents:"
          tar -tzf frontend-build.tar.gz | head -10

      - name: Upload backend
        uses: actions/upload-artifact@v4
        with:
          name: server-backend
          path: server
          if-no-files-found: error

      - name: Upload frontend archive
        uses: actions/upload-artifact@v4
        with:
          name: frontend-archive
          path: frontend-build.tar.gz
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: server-backend
          path: server

      - name: Download frontend archive
        uses: actions/download-artifact@v4
        with:
          name: frontend-archive
          path: .

      - name: Deploy backend to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "server/*"
          target: "/home/ubuntu/MyGroupFullStak/server"

      - name: Deploy frontend archive to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "frontend-build.tar.gz"
          target: "/tmp/"

      - name: Deploy and restart services
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
              # Deploy frontend files
              echo "=== Deploying frontend files ==="

              # Check if archive exists
              if [ -f "/tmp/frontend-build.tar.gz" ]; then
                  echo "✅ Archive found: $(ls -lh /tmp/frontend-build.tar.gz)"
                  echo "Archive contents:"
                  tar -tzf /tmp/frontend-build.tar.gz | head -10
              else
                  echo "❌ Archive not found at /tmp/frontend-build.tar.gz"
                  echo "Files in /tmp:"
                  ls -la /tmp/
                  exit 1
              fi

              sudo rm -rf /var/www/html/*

              # Extract and deploy frontend
              cd /tmp
              tar -xzf frontend-build.tar.gz -C /var/www/html/

              # Set permissions
              sudo chown -R www-data:www-data /var/www/html
              sudo chmod -R 755 /var/www/html

              # Verify files were extracted
              echo "=== Verifying extracted files ==="
              ls -la /var/www/html/

              # Check for index.html specifically
              if [ -f "/var/www/html/index.html" ]; then
                  echo "✅ index.html found"
                  echo "File size: $(du -h /var/www/html/index.html)"
              else
                  echo "❌ index.html not found"
                  echo "Available files:"
                  find /var/www/html/ -type f | head -10
              fi

              # Navigate to app directory
              cd /home/ubuntu/MyGroupFullStak

              # Install backend dependencies if needed
              npm install --production

              # Restart backend application
              pm2 restart all || pm2 start dist/index.js --name "mygroup-app"

              # Clear Nginx cache and reload
              sudo nginx -s reload

              # Add cache-busting headers to force browser refresh
              echo "Cache cleared at $(date)" | sudo tee /var/www/html/cache-bust.txt

              # Clean up temp files
              rm -f /tmp/frontend-build.tar.gz

              # Show status
              echo "=== PM2 Status ==="
              pm2 status
              echo "=== Nginx Status ==="
              sudo systemctl status nginx --no-pager -l

      - name: Verify deployment
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
              echo "=== Verifying Frontend Deployment ==="
              ls -la /var/www/html/
              echo ""
              echo "=== Checking if index.html exists ==="
              if [ -f "/var/www/html/index.html" ]; then
                  echo "✅ Frontend deployed successfully"
                  echo "File size: $(du -h /var/www/html/index.html)"
              else
                  echo "❌ Frontend deployment failed - index.html not found"
                  exit 1
              fi
              echo ""
              echo "=== Testing Frontend Response ==="
              curl -I http://localhost/ || echo "Frontend not responding"
              echo ""
              echo "=== Testing Backend API ==="
              curl -I http://localhost:5000/api/ || echo "Backend API not responding"

