name: CI - Build & Deploy (Frontend + Backend)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm i
          fi

      # Build React frontend
      - name: Build React (Vite)
        run: npm run build:web

      # Move frontend build into a safe place
      - name: Save frontend build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: dist
          if-no-files-found: error

      # Save backend code (server folder)
      - name: Save backend
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: server
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download frontend
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: dist

      - name: Download backend
        uses: actions/download-artifact@v4
        with:
          name: backend
          path: server

      # Deploy backend to EC2
      - name: Deploy backend to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "server/*"
          target: "/home/ubuntu/MyGroupFullStak/server"

      # Deploy frontend to Nginx
      - name: Deploy frontend to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "dist/*"
          target: "/var/www/html"

      # Restart services
      - name: Restart Backend + Reload Nginx
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/MyGroupFullStak/server
            npm install --omit=dev
            pm2 restart all
            sudo systemctl reload nginx
