name: CI - Build & Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: |
          npm ci

      - name: Build React App from Client Directory
        run: npm run build:client

      - name: Upload backend
        uses: actions/upload-artifact@v4
        with:
          name: server-backend
          path: server
          if-no-files-found: error

      - name: Upload frontend dist
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: dist/public
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: server-backend
          path: server

      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: dist/public

      - name: Deploy backend to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "server/*"
          target: "/home/ubuntu/MyGroupFullStak/server"

      - name: Deploy frontend to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "dist/public/"
          target: "/tmp/"
          strip_components: 2

      - name: Deploy and restart services
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
              # Deploy frontend files
              sudo rm -rf /var/www/html/*
              sudo cp -r /tmp/public/* /var/www/html/
              sudo chown -R www-data:www-data /var/www/html
              sudo chmod -R 755 /var/www/html

              # Navigate to app directory
              cd /home/ubuntu/MyGroupFullStak

              # Install backend dependencies if needed
              npm install --production

              # Restart backend application
              pm2 restart all || pm2 start dist/index.js --name "mygroup-app"

              # Clear Nginx cache and reload
              sudo nginx -s reload

              # Add cache-busting headers to force browser refresh
              echo "Cache cleared at $(date)" | sudo tee /var/www/html/cache-bust.txt

              # Clean up temp files
              rm -rf /tmp/public

              # Show status
              echo "=== PM2 Status ==="
              pm2 status
              echo "=== Nginx Status ==="
              sudo systemctl status nginx --no-pager -l

      - name: Verify deployment
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
              echo "=== Verifying Frontend Deployment ==="
              ls -la /var/www/html/
              echo ""
              echo "=== Checking if index.html exists ==="
              if [ -f "/var/www/html/index.html" ]; then
                  echo "✅ Frontend deployed successfully"
                  echo "File size: $(du -h /var/www/html/index.html)"
              else
                  echo "❌ Frontend deployment failed - index.html not found"
                  exit 1
              fi
              echo ""
              echo "=== Testing Frontend Response ==="
              curl -I http://localhost/ || echo "Frontend not responding"
              echo ""
              echo "=== Testing Backend API ==="
              curl -I http://localhost:5000/api/ || echo "Backend API not responding"

